@startmindmap
<style>
mindmapDiagram {
    .root {
        BackgroundColor #333333
        FontColor #FFFFFF
        RoundCorner 150
        FontSize 28
        Padding 20
        LineThickness 5
    }
    .green * {
        BackgroundColor lightgreen
    }
    .rose * {
        BackgroundColor #FFBBCC
    }
    .blue * {
        BackgroundColor lightblue
    }    
}
</style>
*:AZ-305
  Dati; <<root>>
** Az Storage-account <<rose>>
*** Servizi
**** [Blob]
*****        {{Tipo}}
******          Standard v2
******          Premium-BlockBlobStorage
*****        {{Livelli accesso}}
******          Hot-Frequente
******          Cool-sporadico
*******            Min 30gg
******          Cold-freddo
*******            Min 90gg
******          Archive-archivio
*******            Min 180gg
******          WORM
*******            Sola lettura 
*******            Blocchi
********            Temporali 
********            Giudiziari
*****        {{Considerazioni}} 
******          Posizione-Region 
******          Conformità 
******          Costi 
******          Replica
*******            Separare critici 
********              Replica area secondaria 
*******            Area primaria 
********              Lrs
********              Zrs
*******            Area secondaria 
********              Grs
********              Gzrs
******          Carico amm.tivo
******          Riservatezza
******          Isolamento
****      [File]
*****        {{Metodo accesso}} 
******          Diretto-SMB
******          Sincronizzazione locale-cache
*****        {{Prestazioni}} 
******          Standard-hdd
******          Premium-sdd
*******            Lrs-zrs only
******          Netapp-altissime Prestazioni
****      [Dischi]
*****        {{Tipologie}}
******            Ultra-sql
******            Premium v2
******            Premium 
******            Standard-app
******            Hdd Standard-backup
*****        {{Crittografia}}
******            Livello 
*******              Disco-ADE Az disk encription
********                CPU vm-bitlocker
********                Key in az keyvault
********                No Dati temp e cache
********                Ritiro 2028 -> host encr.
********                X legacy
*******              server SSE
********                default-az storage
********                Dischi gestiti
********                No Dati temp e cache
*******              host
********                Dischi gestiti
********                * Dati temporanei e cache
********                X Dati sensibili/regolamenti 
***    (Sicurezza)
****        [Baseline]
***** {{Framework riferimento}}
****        [SAS]
****        [Firewall rules]
****        [Private endpoint]
****        ['Secure transfer required=true']
****        [customer-managed keys]

left side
**  Tipologia
*** Non relazionali -> NoSql
**** Semi-strutturati
***** Json-xml
**** Non strutturati -> Az Storage Account
***** Video-audio
***** Txt-pdf-pptx..
*** Relazionali -> Sql Server
*** Integrazione

** sql <<green>>
*** modelli prezzo 
**** DTU Model
***** combinata
******_ Core
******_ storage
******_ I/O
***** legacy
***** semplice
**** VCore
***** provisioned
******_ scelta vCore/RAM/Tipo storage/service tier
***** serverless
******_ dinamico/a consumo
******_ solo per Gen Purpose (service tier)
******_ x carico sporadico/intermittente
*** Servizi
**** sqlServer VM
***** x Max compatibilità
***** IAAS Agent Extension
**** Mng instance
***** single
****** x compatibilità
*******_ sql agent
*******_ CLR
*******_ trans distribuite
****** max 
*******_ 500 DB
*******_ 32 Tb
***** pool
******_ x tanti piccoli db
**** AZ Db
***** single
****** offerta gratuita fino a 10Gb
****** Max
*******_ 100 Tb
*******_ 100.000 sec VCore
****** modello prezzo
******* DTU -> service tier
******** basic -> 5 DTU
******** standard -> 100 DTU
******** premium -> 1000 DTU
******* Vcore -> service tier
******** Gen Purpose
******** Business Critical
******** Hyperscale
***** elastic pool
****** x molti db piccoli/indipendenti
******* paghi solo 1 (il pool)
******* scalabilità verticale
****** modelli prezzo
******* DTU model -> service tier
******** standard
******** premium
******* Vcore -> service tier
******** Gen Purpose
*** Sicurezza
**** rest
*****:TDE
 Transperent
 Data
 Encryption;
**** transit
***** TLS 1.2
**** use
***** Dynamic Data Masking

** NoSql <<blue>>
*** cosmosDB
*** caratteristiche
**** Bassa Latenza
**** Replica Globale
***** Dati + Nodi
***** Scala orizzontalmente

** Az Data factory ADF
@endmindmap